# Generated by Django 4.2.14 on 2024-11-27 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E (P3)', 'E (P3)'), ('E (P4)', 'E (P4)'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O')], max_length=10)),
                ('employment_no', models.CharField(max_length=100, unique=True)),
                ('contact_address', models.TextField()),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_no', models.CharField(max_length=100)),
                ('annual_leave_entitlement', models.IntegerField()),
                ('leave_days_taken', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(choices=[('A', 'Chief Secretary, Chief Justice'), ('B', 'Deputy Chief Secretary, Secretary to Treasury'), ('C', 'Principal Secretary'), ('D', 'Director'), ('E (P3)', 'Deputy Director (P3)'), ('E (P4)', 'Deputy Director (P4)'), ('F', 'Head of Section (Chief Accountant, Chief HR Officer)'), ('G', 'Principal Accountant, Principal HR Officer'), ('H', 'Senior Officer'), ('I', 'Officer'), ('J', 'Senior Assistant Officer'), ('K', 'Assistant Officer'), ('L', 'Senior Clerk'), ('M', 'Clerk'), ('N', 'Driver, Cleaner'), ('O', 'Driver, Cleaner')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('contact_address_during_leave', models.TextField(blank=True)),
                ('leave_grant_requested', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('HR Approved', 'HR Approved'), ('Supervisor Approved', 'Supervisor Approved'), ('Head Approved', 'Head Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('action_date', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('approver_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leaverequest')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
