# Generated by Django 4.2.14 on 2024-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='contact_address_during_leave',
            field=models.TextField(blank=True, null=True),
        ),
    ]
