# Generated by Django 4.2.14 on 2024-11-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_leaverequest_contact_address_during_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('HR', 'HR'), ('Supervisor', 'Supervisor'), ('Head of Department', 'Head of Department'), ('Employee', 'Employee')], max_length=100, unique=True),
        ),
    ]
