# Generated by Django 4.2.14 on 2024-12-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_leaverequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapproval',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapproval',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
