# Generated by Django 4.2.14 on 2024-12-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_leaveapproval_is_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(choices=[('HR', 'HR'), ('Supervisor', 'Supervisor'), ('Head of Department', 'Head of Department'), ('Employee', 'Employee'), ('System Administrator', 'System Administrator')], max_length=100, unique=True),
        ),
    ]
