# Generated by Django 4.2.14 on 2024-12-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_role_role_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='number_of_days',
        ),
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_entitlement',
            field=models.IntegerField(default=28),
        ),
    ]
